stages:
  - build
  - test
  - e2e

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  DOCKER_TLS_CERTDIR: ''
  DENO_DIR: $CI_PROJECT_DIR/.deno_cache

default:
  image: denoland/deno:latest
  cache:
    - key:
        prefix: $CI_JOB_NAME
        files:
          - backend/deno.lock
          - frontend/deno.lock
      paths:
        - .deno_cache/
    - key:
        prefix: $CI_JOB_NAME
        files:
          - .ci/backend_integration_packages.txt
          - .ci/e2e/packages.txt
      paths:
        - .apt-cache/lists/
        - .apt-cache/archives/
    - key: exam-toolbox-e2e-cache
      paths:
        - .npm_cache/
    - key: $CI_PROJECT_NAME-tectonic
      paths:
        - .cache/Tectonic

checks:
  stage: .pre
  script:
    - deno x prettier --check **/*.{ts,html,scss,json,yaml,yml,md}
    - bash ./tools/check_shared_types.sh

backend_build:
  stage: build
  before_script:
    - cd backend
    - deno install -q
  script:
    - deno task build

frontend_build:
  stage: build
  before_script:
    - cd frontend
    - deno install -q
  script:
    - deno run ng build --configuration production --no-watch --no-progress --watch=false
  rules:
    - when: never # Right now it does not complete, probably because it does not become stable during pre-rendering

backend_tests:
  stage: test
  before_script:
    - bash .ci/prepare_backend_integration.sh .ci/backend_integration_packages.txt
    - cd backend
    - deno install -q
  script:
    - deno check
    - deno run cover
  coverage: '/All files[^|]*|[^|]*\s+([\d\.]+)/'

cypress_e2e:
  stage: e2e
  image:
    name: cypress/included:15.18.1
    entrypoint: ['']
  services:
    - name: osixia/openldap:1.5.0
      alias: ldap-host
      variables:
        LDAP_ORGANISATION: 'University'
        LDAP_DOMAIN: university.example
        LDAP_BASE_DN: dc=university,dc=example
        LDAP_READONLY_USER: 'True' # username: "readonly", pw: "readonly"
    - name: mongo:8
      command: ['--replSet', 'rs0']
    - name: marlonb/mailcrab:latest
      alias: mailcrab
  variables:
    DB_CONNSTRING: mongodb://mongo:27017/examToolboxDB?directConnection=true&replicaSet=rs0
    AUTH_LDAP_URL: 'ldap://ldap-host:389'
    AUTH_LDAP_BIND_DN: 'cn=readonly,dc=university,dc=example'
    AUTH_LDAP_BIND_PASSWORD: 'readonly'
    AUTH_LDAP_USER_SEARCH_BASE: 'ou=users,ou=accounts,dc=university,dc=example'
    AUTH_LDAP_GROUP_DN_BASE: 'cn=%s,ou=groups,ou=accounts,dc=university,dc=example'
    AUTH_LDAP_GROUPS_REQUIRED: 'toolboxUsers'
    AUTH_LDAP_GROUPS_ADMIN: 'admins'
    AUTH_LDAP_GROUPS_FULL: 'teachers'
    AUTH_JWT_SECRET: 'ad06569335976252a1cea6ee4521f0c33e2fa93507e228a053dc8b75f3418312'
    SMTP_HOST: mailcrab
    SMTP_PORT: 1025
    SMTP_FROM: noreply@example.com
    SERVER_PUBLIC_URL: 'http://localhost'
    PATHS_TEMPLATE_BASE_PATH: '${CI_PROJECT_DIR}/backend/template'
    PATHS_CACHE_DIR: /tmp/cache
    PATHS_JOBS_DIR: /tmp/jobs
    QR_MIN_STUDENTS: 3
    QR_MIN_PAGES: 6
    TECTONIC_VERSION: '0.16.9'
  before_script:
    - bash .ci/prepare_backend_integration.sh .ci/backend_integration_packages.txt
    - bash .ci/prepare_backend_integration.sh .ci/e2e/packages.txt
    - npm config set cache ${CI_PROJECT_DIR}/.npm_cache && npm i --allow-scripts deno -g deno >/dev/null
    - bash -c 'cd backend && deno install -q'
    - bash -c 'cd frontend && deno install -q'
    - mkdir -p /tmp/cache /tmp/jobs /tmp/uploads # For caddy
    - ldapadd -f ldap/10-testuser.ldif -D cn=admin,dc=university,dc=example -w admin -H ldap://ldap-host:389 > /dev/null
    - bash .ci/e2e/tectonic.sh
    - bash .ci/e2e/mongo_init.sh # We need to init the replica set here because mongo cannot resolve it own hostname
  script:
    - bash .ci/e2e/start.sh
    - cypress run --config-file cypress/cypress.config.ts --quiet
  artifacts:
    when: always
    paths:
      - .logs/*.log
      - cypress/screenshots/**/*.png
    expire_in: 1 day
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
      when: always
    - if: $CI_COMMIT_BRANCH == "dev"
      when: manual
      allow_failure: true
