stages:
  - test

image: docker:25.0.5

variables:
  DOCKER_TLS_CERTDIR: ""

backend_unittests:
  image: denoland/deno:latest
  stage: test
  script:
    - cd backend
    - deno test

# Cypress Tests
cypress_e2e:
  stage: test
  image: cypress/base:20.9.0
  services:
    - docker:25.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    # default from documentation: https://docs.docker.com/engine/install/debian/
    - apt-get update
    - apt-get install -y ca-certificates curl
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    - chmod a+r /etc/apt/keyrings/docker.asc
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - apt-get update
    - apt-get install -y docker-ce-cli docker-compose-plugin
  script:
    - DOCKER_IP=$(getent hosts docker | awk '{print $1}')
    - sed -i "s/127\.0\.0\.1.*localhost/$DOCKER_IP\tlocalhost/" /etc/hosts
    - docker compose up -d --build
    - cd frontend
    - npm install
    - echo "--- CONTAINER STATUS ---"
    - docker compose ps
    - echo "--- CADDY LOGS ---"
    - docker compose logs caddy
    - export NODE_TLS_REJECT_UNAUTHORIZED=0
    - npx wait-on tcp:localhost:443 -t 60000
    - npx cypress run --config baseUrl=https://localhost,video=false
  after_script:
    - docker compose down
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "dev"
      when: manual
      allow_failure: true
    - when: never
