services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/examToolboxDB # Adjust your DB name
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80" # Adjust if necessary

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 

