services:
  # documentation (basic usage): ofhttps://hub.docker.com/_/caddy
  # auto-generates crypto key (https://docs.authcrunch.com/docs/authenticate/auth-cookie)
  # also possible to set a key manually, for better persistance (and possible other advantages). Not needed here for now.
  caddy:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data # https://caddyserver.com/docs/conventions#data-directory
      - ./caddy/conf:/etc/caddy
    networks:
      - web
    depends_on:
      - backend
    environment:
      DOMAIN: ${DOMAIN} # needs to be changed for production (with domain)

  backend:
    build:
      context: ./backend
    # ports: # not exposed when caddy is used
    #   - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/config.yaml:/app/config.yaml
      - backend_cache:/app/cache
      - backend_jobs:/app/jobs
    environment:
      DB_CONNSTRING: mongodb://mongo:27017/examToolboxDB
      AUTH_LDAP_URL: "ldap://ldap-host:389"
      AUTH_LDAP_BIND_DN: "cn=readonly,dc=university,dc=example"
      AUTH_LDAP_BIND_PASSWORD: "readonly"
      AUTH_LDAP_USER_SEARCH_BASE: "ou=users,ou=accounts,dc=university,dc=example"
      AUTH_LDAP_GROUP_DN_BASE: "cn=%s,ou=groups,ou=accounts,dc=university,dc=example"
      AUTH_LDAP_GROUPS_REQUIRED: "toolboxUsers"
      AUTH_LDAP_GROUPS_ADMIN: "admins"
      AUTH_LDAP_GROUPS_FULL: "teachers"
      AUTH_JWT_SECRET: "ad06569335976252a1cea6ee4521f0c33e2fa93507e228a053dc8b75f3418312"
      SMTP_HOST: mailcrab
      SMTP_PORT: 1025
      SMTP_FROM: noreply@example.com
      SERVER_DOMAIN: ${DOMAIN}
      SERVER_HTTPS: true
      PATHS_CACHE_DIR: /app/cache
      PATHS_JOBS_DIR: /app/jobs
      CONFIG: /app/config.yaml
    depends_on:
      - mongo
      - mailcrab
    networks:
      - web
    develop:
      watch:
        - path: ./backend/
          include:
            - "**/*.ts"
            - "server.ts"
          action: sync
          target: /app/
        - path: backend/template/
          action: rebuild

  mailcrab:
    image: marlonb/mailcrab:latest
    container_name: mailcrab
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - web

  # not needed when caddy hosts static frontend build files
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "4200:80"
  #   networks:
  #     - web

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - web

  ldap-host:
    image: osixia/openldap:1.5.0
    command: --copy-service # --loglevel debug # Do not overwrite custom ldif files
    restart: unless-stopped
    networks:
      web:
    environment:
      OPENLDAP_DEBUG_LEVEL: 256 # See Table 7.1 at https://www.openldap.org/doc/admin24/runningslapd.html
      LDAP_ORGANISATION: "University"
      LDAP_DOMAIN: university.example
      LDAP_BASE_DN: dc=university,dc=example
      LDAP_ADMIN_PASSWORD: "admin" # LDAP Admin Login: cn=admin,dc=university,dc=example
      LDAP_READONLY_USER: "True" # username: "readonly", pw: "readonly"
    volumes:
      # make users/config persistent
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldap/:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro

  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    restart: unless-stopped
    networks:
      web:
    ports:
      - "6080:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-host
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - ldap-host

  periodic-tasks:
    build:
      context: ./periodical
    volumes:
      - backend_jobs:/app/jobs

volumes:
  mongodb_data:
  caddy_data:
  caddy_config:
  ldap_data:
  ldap_config:
  backend_jobs:
  backend_cache:

networks:
  web:
    driver: bridge
