info:
  name: List all tasks
  type: http
  seq: 1
  tags:
    - Tasks

http:
  method: GET
  url: "{{baseUrl}}/api/taskPool"
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Task list
    request:
      url: "{{baseUrl}}/api/taskPool"
      method: GET
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          [
            {}
          ]

docs: Returns all tasks in the pool.
