info:
  name: Tasks by creator
  type: http
  seq: 7
  tags:
    - Tasks

http:
  method: GET
  url: "{{baseUrl}}/api/taskPool/user/:userId"
  params:
    - name: userId
      value: ""
      type: path
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Tasks by user
    request:
      url: "{{baseUrl}}/api/taskPool/user/:userId"
      method: GET
      params:
        - name: userId
          value: ""
          type: path
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          [
            {}
          ]

docs: Returns tasks created by the specified user.
